//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLSOCweb.ServiceReference5 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timetablesc", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Timetablesc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LechallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LecnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch {
            get {
                return this.BatchField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchField, value) != true)) {
                    this.BatchField = value;
                    this.RaisePropertyChanged("Batch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lab {
            get {
                return this.LabField;
            }
            set {
                if ((object.ReferenceEquals(this.LabField, value) != true)) {
                    this.LabField = value;
                    this.RaisePropertyChanged("Lab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lechall {
            get {
                return this.LechallField;
            }
            set {
                if ((object.ReferenceEquals(this.LechallField, value) != true)) {
                    this.LechallField = value;
                    this.RaisePropertyChanged("Lechall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lecname {
            get {
                return this.LecnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LecnameField, value) != true)) {
                    this.LecnameField = value;
                    this.RaisePropertyChanged("Lecname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modcode {
            get {
                return this.ModcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModcodeField, value) != true)) {
                    this.ModcodeField = value;
                    this.RaisePropertyChanged("Modcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Feedbacksc", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Feedbacksc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faculty {
            get {
                return this.FacultyField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyField, value) != true)) {
                    this.FacultyField = value;
                    this.RaisePropertyChanged("Faculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Feedback {
            get {
                return this.FeedbackField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedbackField, value) != true)) {
                    this.FeedbackField = value;
                    this.RaisePropertyChanged("Feedback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modcode {
            get {
                return this.ModcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModcodeField, value) != true)) {
                    this.ModcodeField = value;
                    this.RaisePropertyChanged("Modcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.IService5")]
    public interface IService5 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/Login", ReplyAction="http://tempuri.org/IService5/LoginResponse")]
        int Login(SLSOCweb.ServiceReference5.Users ud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/Login", ReplyAction="http://tempuri.org/IService5/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(SLSOCweb.ServiceReference5.Users ud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/GetComTimetables", ReplyAction="http://tempuri.org/IService5/GetComTimetablesResponse")]
        SLSOCweb.ServiceReference5.Timetablesc[] GetComTimetables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/GetComTimetables", ReplyAction="http://tempuri.org/IService5/GetComTimetablesResponse")]
        System.Threading.Tasks.Task<SLSOCweb.ServiceReference5.Timetablesc[]> GetComTimetablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/GetBusTimetables", ReplyAction="http://tempuri.org/IService5/GetBusTimetablesResponse")]
        SLSOCweb.ServiceReference5.Timetablesc[] GetBusTimetables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/GetBusTimetables", ReplyAction="http://tempuri.org/IService5/GetBusTimetablesResponse")]
        System.Threading.Tasks.Task<SLSOCweb.ServiceReference5.Timetablesc[]> GetBusTimetablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/GetEngTimetables", ReplyAction="http://tempuri.org/IService5/GetEngTimetablesResponse")]
        SLSOCweb.ServiceReference5.Timetablesc[] GetEngTimetables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/GetEngTimetables", ReplyAction="http://tempuri.org/IService5/GetEngTimetablesResponse")]
        System.Threading.Tasks.Task<SLSOCweb.ServiceReference5.Timetablesc[]> GetEngTimetablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/AddFeedback", ReplyAction="http://tempuri.org/IService5/AddFeedbackResponse")]
        int AddFeedback(SLSOCweb.ServiceReference5.Feedbacksc fbd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/AddFeedback", ReplyAction="http://tempuri.org/IService5/AddFeedbackResponse")]
        System.Threading.Tasks.Task<int> AddFeedbackAsync(SLSOCweb.ServiceReference5.Feedbacksc fbd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService5Channel : SLSOCweb.ServiceReference5.IService5, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service5Client : System.ServiceModel.ClientBase<SLSOCweb.ServiceReference5.IService5>, SLSOCweb.ServiceReference5.IService5 {
        
        public Service5Client() {
        }
        
        public Service5Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service5Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service5Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service5Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(SLSOCweb.ServiceReference5.Users ud) {
            return base.Channel.Login(ud);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(SLSOCweb.ServiceReference5.Users ud) {
            return base.Channel.LoginAsync(ud);
        }
        
        public SLSOCweb.ServiceReference5.Timetablesc[] GetComTimetables() {
            return base.Channel.GetComTimetables();
        }
        
        public System.Threading.Tasks.Task<SLSOCweb.ServiceReference5.Timetablesc[]> GetComTimetablesAsync() {
            return base.Channel.GetComTimetablesAsync();
        }
        
        public SLSOCweb.ServiceReference5.Timetablesc[] GetBusTimetables() {
            return base.Channel.GetBusTimetables();
        }
        
        public System.Threading.Tasks.Task<SLSOCweb.ServiceReference5.Timetablesc[]> GetBusTimetablesAsync() {
            return base.Channel.GetBusTimetablesAsync();
        }
        
        public SLSOCweb.ServiceReference5.Timetablesc[] GetEngTimetables() {
            return base.Channel.GetEngTimetables();
        }
        
        public System.Threading.Tasks.Task<SLSOCweb.ServiceReference5.Timetablesc[]> GetEngTimetablesAsync() {
            return base.Channel.GetEngTimetablesAsync();
        }
        
        public int AddFeedback(SLSOCweb.ServiceReference5.Feedbacksc fbd) {
            return base.Channel.AddFeedback(fbd);
        }
        
        public System.Threading.Tasks.Task<int> AddFeedbackAsync(SLSOCweb.ServiceReference5.Feedbacksc fbd) {
            return base.Channel.AddFeedbackAsync(fbd);
        }
    }
}
